<?php
namespace app\models;

use yii\mongodb\ActiveRecord;

class MongoChospital extends ActiveRecord {

    public static function collectionName(){
        return 'chospital';
    }

    public function attributes()
    {
        parent::attributes(); // TODO: Change the autogenerated stub
    }
    public static function getDb()
    {
        return \Yii::$app->get('mongodb');
    }

}
?>